# Generated by Django 3.1.7 on 2021-04-19 13:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.CharField(default='{}', max_length=1000)),
                ('totcarts', models.CharField(default='{}', max_length=1000, null=True)),
                ('usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0, null=True)),
                ('rating', models.IntegerField(default=1, null=True)),
                ('rateusers', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.extendeduser')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purd', models.DateTimeField(default=datetime.datetime(2021, 4, 19, 18, 38, 29, 964507), null=True)),
                ('state', models.CharField(default='Nagpur', max_length=50, null=True)),
                ('lat', models.CharField(default='21.1015184', max_length=50, null=True)),
                ('lang', models.CharField(default='78.893078', max_length=50, null=True)),
                ('days', models.IntegerField(default='5', null=True)),
                ('lato', models.CharField(default='21.1015184', max_length=50, null=True)),
                ('lango', models.CharField(default='78.893', max_length=50, null=True)),
                ('purdate', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.extendeduser')),
            ],
        ),
    ]
