# Generated by Django 3.1.7 on 2021-04-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210414_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='pur',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='pur',
            field=models.ManyToManyField(to='accounts.PurchaseDate'),
        ),
    ]
