# Generated by Django 3.1.7 on 2021-04-14 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210414_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='pur',
        ),
        migrations.AlterField(
            model_name='purchasedate',
            name='purdate',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.extendeduser'),
        ),
    ]
