# Generated by Django 3.1.7 on 2021-04-14 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210414_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedate',
            name='purd',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 18, 32, 55, 531699), null=True),
        ),
    ]
