# Generated by Django 3.1.7 on 2021-04-15 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_purchasedate_purd'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedate',
            name='days',
            field=models.IntegerField(default='5', null=True),
        ),
        migrations.AddField(
            model_name='purchasedate',
            name='lang',
            field=models.CharField(default='78.893078', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedate',
            name='lat',
            field=models.CharField(default='21.1015184', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedate',
            name='state',
            field=models.CharField(default='Nagpur', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedate',
            name='purd',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 15, 22, 11, 597449), null=True),
        ),
    ]
