# Generated by Django 3.1.7 on 2021-04-15 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210415_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedate',
            name='lango',
            field=models.CharField(default='78.893078', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedate',
            name='lato',
            field=models.CharField(default='21.1015184', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedate',
            name='purd',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 17, 14, 10, 771981), null=True),
        ),
    ]
