# Generated by Django 3.1.7 on 2021-04-24 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20210422_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedate',
            name='purd',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 14, 7, 40, 311662), null=True),
        ),
    ]
