# Generated by Django 3.1.7 on 2021-04-24 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210424_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='auth_token',
            field=models.CharField(default='No auth', max_length=100),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchasedate',
            name='purd',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 17, 32, 38, 774178), null=True),
        ),
    ]
