# Generated by Django 3.1.7 on 2021-04-24 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210424_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='auth_token',
            field=models.SlugField(default='No auth', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasedate',
            name='purd',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 17, 50, 55, 585162), null=True),
        ),
    ]
