# Generated by Django 3.1.7 on 2021-04-17 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210417_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedate',
            name='lango',
            field=models.CharField(default='78.893', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedate',
            name='purd',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 11, 0, 23, 459993), null=True),
        ),
    ]
