# Generated by Django 3.1.7 on 2021-04-19 13:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=100)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_desc', models.CharField(max_length=500)),
                ('product_pubs_date', models.DateField(auto_now=True)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('discount', models.IntegerField(default=30)),
                ('offers', models.CharField(default='', max_length=500)),
                ('subcategory1', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('image1', models.ImageField(default='', upload_to='shop/images1')),
                ('rating', models.FloatField(default=1, null=True)),
                ('num', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.CharField(default='1', max_length=50, null=True)),
                ('username', models.CharField(default='User', max_length=50, null=True)),
                ('cmt_title', models.CharField(default='Title', max_length=100, null=True)),
                ('cmt_desc', models.CharField(default='This is a demo desc...', max_length=500, null=True)),
                ('rating', models.IntegerField(default=3, null=True)),
                ('edited', models.BooleanField(default=False)),
                ('edit_time', models.DateTimeField(default=datetime.datetime(2021, 4, 19, 18, 38, 37, 670702))),
                ('cmt_time', models.DateTimeField(default=datetime.datetime(2021, 4, 19, 18, 38, 37, 670702))),
                ('product_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
