# Generated by Django 3.0.3 on 2021-03-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=8)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_desc', models.CharField(max_length=300)),
            ],
        ),
    ]
