# Generated by Django 3.1.7 on 2021-04-19 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='cmt_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 18, 52, 39, 631101)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='edit_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 18, 52, 39, 631101)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='', null=True, upload_to='shop/images1'),
        ),
    ]
