# Generated by Django 3.0.3 on 2021-03-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_product_pubs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pubs_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
