# Generated by Django 3.1.7 on 2021-04-19 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210419_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='cmt_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 18, 56, 12, 473566)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='edit_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 18, 56, 12, 473566)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='', upload_to='shop/images1'),
        ),
    ]
