# Generated by Django 3.1.7 on 2021-04-21 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210419_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateNow', models.DateTimeField(blank=True, null=True)),
                ('dateEnd', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='cmt_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 23, 5, 20, 858633)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='edit_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 23, 5, 20, 858633)),
        ),
    ]
