# Generated by Django 3.1.7 on 2021-04-21 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210422_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='cmt_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 2, 1, 23, 744828)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='edit_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 2, 1, 23, 744828)),
        ),
    ]
