# Generated by Django 3.1.7 on 2021-04-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210421_2055'),
        ('shop', '0008_auto_20210422_0201'),
    ]

    operations = [
    ]
