# Generated by Django 3.1.7 on 2021-04-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210417_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.CharField(default='1', max_length=50, null=True)),
                ('username', models.CharField(default='User', max_length=50, null=True)),
                ('cmt_title', models.CharField(default='Title', max_length=100, null=True)),
                ('cmt_desc', models.CharField(default='This is a demo desc...', max_length=500, null=True)),
                ('rating', models.IntegerField(default=3, null=True)),
                ('product_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
