# Generated by Django 3.1.7 on 2021-04-17 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='cmt_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 17, 42, 18, 78277)),
        ),
        migrations.AddField(
            model_name='comments',
            name='edit_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 17, 42, 18, 78277)),
        ),
        migrations.AddField(
            model_name='comments',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
